package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u91/6644/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, April 1, 2016 1:02:16 AM PDT
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
   * state is changed.
   */
  public static final short value = (short)(0);
}
